export default {
  ADD: 'ADD',
  MINUS: 'MINUS',
  UPDATE_GAPI_IS_LOADED: 'UPDATE_GAPI_IS_LOADED',
  UPDATE_GOOGLE_SIGNED_IN: 'UPDATE_GOOGLE_SIGNED_IN',
  UPDATE_DB_URL: 'UPDATE_DB_URL',
  UPDATE_DB_FILE: 'UPDATE_DB_FILE',
  CREATE_DB_URL: 'CREATE_DB_URL',
  LOAD_DB: 'LOAD_DB',
};
